pipeline {
  agent {
    docker {
      image 'node:6-alpine'
      args '-p 3000:3000'
    }

  }
  stages {
    stage('Automation E2E tests') {
      parallel {
        stage('Full UI Tests') {
            steps {
                sh 'echo  \"Full UI Tests\"'
            }
        }
        stage('Full DV Tests') {
            steps {
                sh 'echo  \"Full UI Tests\"'
            }
        }
      }
    }
  }
}
